### PR TITLE
feat: Add arm64 support.

### LINKED ISSUE #11: Add support for arm64 machine
On a regular arm64 machine, terra suggests to use cosmwasm/rust-optimizer-arm64:0.12.4 as the docker image for optimization which will produce an artifact at `artifacts/<contract-name>-aarch64.wasm` which is different from non-arm one. Right now `terrain` doesn't support this option which results in a failure after `terrain deploy` command.

### PR DESCRIPTION
**Pull request by octalmage**
While testing on my M1 Mac I ran into a few issues optimizing and deploying my contract. These changes update Terrain to use the `rust-optimizer-arm64` image when optimizing on an arm64 device which produces an artifact with the `-aarch64` suffix. 

Resolves #11.

### CODE REVIEW

**Comment by iboss-ptk** [comment]
afaik, `rust-optimizer-arm64` produce binary that is advised to use only in dev:

quoted from [rust-optimizer repo](https://github.com/CosmWasm/rust-optimizer#notice)
> Arm images are released to ease development and testing on Mac M1 machines. For release / production use, only contracts built with the Intel optimizers must be used.

SoI have 2 points here:
1. Weird thing about this is that I'm on m1 and I don't have any problem using non `-arm-64` image and seems like @ WasinWatt (#11 issuer) does not face the problem anymore, does your m1 have rosetta installed at all? Trying to figure out the actual cause here.
2. If we found out that `-arm64` image is still needed, we should make it explicit eg. by passing the flag so that user knows that it is not advised to use that binary for production.

**Comment by WasinWatt** [comment]
Yeah, so that only happened to me locally. I couldn't deploy to `localterra` without `rust-optimizer-arm64` but I could deploy to `testnet` without it.

**Comment by octalmage** [comment]
That was also my experience, let me do some more testing today. I totally agree with the points made by @iboss-ptk, should be a flag if we decide to add it.

**Comment by octalmage** [comment]
Closing, all seems to be working as far as I can tell!

**Comment by yuc0rp** [comment]
M1 Max ARM64 here, with activated rosetta ( i think i did some time ago ):

The default used AMD64 container of rust optimizer with QEMU for x64 instead M1 / ARM64 is totally wrecking up my complete docker socket, not responding anymore, if i run `docker ps`, it takes ages for any response, MacOS 12 Docker Desktop stats/inspect is freezing, when the optimizer is running at the step ( `❯ terrain deploy counter --signer validator` )

additionally, i am also getting the following error / crash, following the docs tutorial:

```
Building contract in /code ...
    Updating crates.io index
Killed
Finished, status of exit status: **137** ( :D )
    Error: ENOENT: no such file or directory, open 'artifacts/counter.wasm'
    Code: ENOENT
```

opening the PR / issue would be kinda logical step now :)

**Comment by yuc0rp** [comment]
Screen Shot 2022-01-21 at 22 25 07
Screen Shot 2022-01-21 at 22 24 57

these are my settings in docker desktop, could the GB ram allocation | virtualization framework setting be related too ?

**Comment by pkayfire** [comment]
@iboss-ptk @octalmage can you go into more detail on how you were able to deploy to `localterra` on a m1 without issues? I get the same errors as @yuc0rp

**Comment by pkayfire** [comment]
hmm ok it seems like I was able to get it working by reinstalling rust on a terminal with rosetta enabled

**Comment by yuc0rp** [comment]
thats not really a solution. we should deploy crossplatform containers. check `docker buildx`

--

**Comment by yuc0rp** [comment]
we should get the arm64 version of rustc to compile intel wasm's at the end, correct? lets get that done

**Comment by solumos** [comment]
I'm also getting the same errors as @yuc0rp 
```
@iboss/terrain/0.0.8 darwin-arm64 node-v16.13.2
Docker version 20.10.12
```

**Comment by yuc0rp** [comment]
Try increase your docker desktop gigabyte allocation size

**Comment by burke-md** [comment]
Just following up - I am on an apple M1 and have the same error as @yuc0rp.
Was there ever a solution to this problem?

**Comment by octalmage** [comment]
This ended up being the solution:

https://github.com/iboss-ptk/terrain/pull/16#issuecomment-1023774820

2 gb just isn’t enough for the rust optimizer. 6 seems to work best!

**Comment by burke-md** [comment]
Thank you so much for your quick response. Did the trick.

**Pull request closed without merging**
